### PR TITLE
Issue on removing envoy

### PR DESCRIPTION
**Pull request by 7hong13**
#### What are the relevant tickets?

Fixes #

### Checklist

- [ ] Added relevant tests or not required
- [ ] Didn't break anything

### CODE REVIEW

**Comment by 7hong13** [comment]
When modifying the `docker-compose` script to exclude Envoy, the server response for `activateRequest` does not return.

However, it works well in the following script:
```
ervices:
  yorkie:
    image: 'krapi0314/yorkie:test'
    container_name: 'yorkie'
    command: ['server', '--enable-pprof']
    restart: always
    ports:
      - '8080:8080'
      - '8081:8081'
```

**Comment by hackerwins** [comment]
@7hong13 Are there any related logs or error messages?

**Comment by 7hong13** [comment]
> @7hong13 Are there any related logs or error messages?

I'm unable to provide the related logs since sending the `activateClientRequest` doesn't result in either an exception or a response from the server; instead, it just gets stuck at line 126."
https://github.com/yorkie-team/yorkie-android-sdk/blob/99713c1c980ed727e020c2cc9b3ef9cf1c109e63/yorkie/src/main/kotlin/dev/yorkie/core/Client.kt#L125-L136

**Comment by skhugh** [comment]
I believe this is resolved and merged  by https://github.com/yorkie-team/yorkie-android-sdk/pull/167

**Comment by 7hong13** [comment]
Closing it since the issue has been resolved.

**Pull request closed without merging**
